### ISSUE TITLE
No password authentication

### ISSUE THREAD

**Issue by DerpDarako** [mwilliamson/spur.py#17]
Hello,

When I execute this:

shell = spur.SshShell(hostname='IP',
            username='admin',
            password='password')
shell.run('sh ver')

I always get :
spur.ssh.ConnectionError: Error creating SSH connection
Original error: Authentication failed.

From my router, I see public key authentication.

Are you sure to set up look_for_keys to false?

**Comment by mwilliamson** [comment]
I've added a `look_for_private_keys` argument to `SshShell`, which can be set to `False`, which should fix this issue. Sorry for keeping this open so long!

**Comment by DerpDarako** [comment]
Thank you :)
