### ISSUE TITLE
fping command on remote on unreachable ip throws exception

### ISSUE THREAD

**Issue by gradbharath** [mwilliamson/spur.py#18]
cmd =  fping -c 2 -q 10.152.126.25 -s
shell = spur.SshShell(hostname=ip, username="root", password="foo")
x = shell.run(cmd.split(" "))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/spur/ssh.py", line 156, in run
    return self.spawn(_args, *_kwargs).wait_for_result()
  File "/usr/local/lib/python2.7/site-packages/spur/ssh.py", line 353, in wait_for_result
    self._result = self._generate_result()
  File "/usr/local/lib/python2.7/site-packages/spur/ssh.py", line 365, in _generate_result
    stderr_output
  File "/usr/local/lib/python2.7/site-packages/spur/results.py", line 9, in result
    raise result.to_error()
spur.results.RunProcessError: return code: 1
output: b''
stderr output: b'10.152.126.25 : xmt/rcv/%loss = 2/0/100%\n\n       1 targets\n       0 alive\n       1 unreachable\n       0 unknown addresses\n\n       0 timeouts (waiting for response)\n       2 ICMP Echos sent\n       0 ICMP Echo Replies received\n       0 other ICMP received\n\n 0.00 ms (min round trip time)\n 0.00 ms (avg round trip time)\n 0.00 ms (max round trip time)\n        1.517 sec (elapsed real time)\n\n'

I would except x to return with returncode 1 and output instead of the exception

**Comment by kavithab9** [comment]
I execute a bash script using "shell.run()" and do not use allow_error=True yet. I get the desired output but I still get that "spur.results.RunProcessError: return code:1 output: b'" WHy is that?

**Comment by mwilliamson** [comment]
> I execute a bash script using "shell.run()" and do not use allow_error=True yet. I get the desired output but I still get that "spur.results.RunProcessError: return code:1 output: b'" WHy is that?

I'm afraid I don't understand your question. What behaviour are you seeing, and what behaviour do you expect?
