### ISSUE TITLE
Closing SSH connections

### ISSUE THREAD

**Issue by gpiermattei** [mwilliamson/spur.py#24]
After successfully executed my commands, I need to close the SSH connection but I don't no how. I don't know if it is a issue or I don't find the way to close the session.
I checked with "netstat" and the SSH connection remains established until I close the python interpreter.

Could you give me some ideas?

**Comment by mwilliamson** [comment]
Does the connection remain if you use the shell as a context manager? For instance:

```python
shell = spur.SshShell(hostname="localhost", username="bob", password="password1")
with shell:
    result = shell.run(["echo", "-n", "hello"])
```

Doing so closes the underlying Paramiko client, so should close any connections.

**Comment by gpiermattei** [comment]
Problem solved! using 'with' the ssh connection ends perfectly. Thank you very much and great lib!!

**Comment by mwilliamson** [comment]
Glad I could help!
