### ISSUE TITLE
persistant connections ? y/n & a note

### ISSUE THREAD

**Issue by kinovue** [mwilliamson/spur.py#25]
I'm liking spur very

thanks for the effort

My question is I'm in a situation where I'd like to keep a ssh connection open
so that each new command sent does not have to reconnect and authenticate (to save time)

I've only started with spur (and even python)
but is there a "keep active" command available?
or some sort of pattern for that?

 Also I bumped my head against the "shell_type=spur.ssh.ShellTypes.minimal" problem with embedded systems on a Raspberry Pi..
Adding that fixed all my problems [yay]
it might be a good thing to add to the readme that RPi users should use the "shell_type=spur.ssh.ShellTypes.minimal" directive

thanks again

WH

**Comment by gpiermattei** [comment]
Hi, I think this code will help you:

#-----------------------------------------------------------
# Example: 2 commands in 1 session
#-----------------------------------------------------------

import spur

# SSH Server Data:
ip = '192.168.0.83'
user = 'root'
password = 'password'

# Commands to be executed:
command1 = 'vim-cmd vmsvc/getallvms'
command2 = 'ls /'

# Create the session:
session = spur.SshShell(hostname=ip,\
                        username=user,\
                        password=password,\
                        missing_host_key = spur.ssh.MissingHostKey.accept,\
                        shell_type=spur.ssh.ShellTypes.minimal)

# Run the commands and close the SSH Connection
with session:
    result = session.run(command1.split(' '))
    print result.output
    print result.return_code
    result = session.run(command2.split(' '))
    print result.output
    print result.return_code

**Comment by kinovue** [comment]
humm  not sure this would do what I'm hoping to do

(this may because I'm newish to python)
the 'with' statement i'm opening and closing the ssh connection
I'm trying to keep the connection open indefinitely 
i'd like to keep 'session' open until much later in the program when after other computation and a pause
I'd send new commands to 'session' again
I guess maybe a better question is what would be the best pattern to create a open and non blocking ssh connection
do I use a subprocess or is spawning the ssh connection enough...

I will experiment

thanks for the quick response!

WH

**Comment by gpiermattei** [comment]
If you remove the "with" the ssh connection will be open for ever (I think) or untill the timeout
For example:

```python
#-----------------------------------------------------------
# Example: Open session for ever...
#-----------------------------------------------------------

import spur
import time

# SSH Server Data:
ip = '192.168.0.83'
user = 'root'
password = 'my_password'


# Create the session:
session = spur.SshShell(hostname=ip,\
                        username=user,\
                        password=password,\
                        missing_host_key = spur.ssh.MissingHostKey.accept,\
                        shell_type=spur.ssh.ShellTypes.minimal)


command1 = 'ls /'

# Run the commands 
result = session.run(command1.split(' '))
print result.output
print result.return_code

# Wait some time.....
print 'Waiting....'
time.sleep(10)

# Run the commands again
result = session.run(command1.split(' '))
print result.output
print result.return_code

# Wait some time.....
print 'Waiting....'
time.sleep(20)

# Run the commands again
result = session.run(command1.split(' '))
print result.output
print result.return_code
```

**Comment by kinovue** [comment]
Thanks
I'm trying that now
and it seems to work with .run but not so well with .spawn

but I think I've got it

thanks!

**Comment by mwilliamson** [comment]
Glad to hear things are working, and thanks to @gpiermattei for the helpfulness!
