### ISSUE TITLE
spur hangs after child exits in local process

### ISSUE THREAD

**Issue by uzytkownik** [mwilliamson/spur.py#27]
In some circumstances (I haven't discovered what the conditions are) when I use local shell it hangs. The child process is dead but spur has not called `waitpid` (i.e. child is zombie).

The code calling the subprocess is more or less following:

``` python

import spur

local = spur.LocalShell()
spur.run(["git", "push", "ssh://someserver/some/git/repo.git"], cwd="some/local/git/repo", stdout=sys.stdout, stderr=sys.stderr)
```

**Comment by mwilliamson** [comment]
Hmm, I haven't come across this issue myself, so not sure how I would go about reproducing it. If you run the same command, does it happen consistently?

**Comment by uzytkownik** [comment]
No. When I kill the python and run again it works fine. In fact it works fine most of the time.

**Comment by mwilliamson** [comment]
Closing since this is an old issue that I can't reproduce. Happy to reopen if there are reproduction steps or more information.
