### ISSUE TITLE
troubles getting started with spur

### ISSUE THREAD

**Issue by Neetuj** [mwilliamson/spur.py#30]
I run this example with correct hostname nad port and credentails and i get the error stated below. 

"spur.ssh.ConnectionError: Error creating SSH connection
Original error: [Errno -2] Name or service not known"

Using a debugger I see that it does get the shell. 
But the error is raised on shell.run() 

import spur
shell = spur.SshShell(hostname="1.2.3.4:123",username="bla", password="bla")
with shell:
    result = shell.run(["echo", "-n", "hello"])
print result.output

Also if I try to use 
   spur.SshShell(hostname="1.2.3.4", port=123,username="bla", password="bla")
it fails saying "Original error: Server '1.2.3.4:123' not found in known_hosts" but does not complain if i use this-->
spur.SshShell(hostname="1.2.3.4:123",username="bla", password="bla")

**Comment by mwilliamson** [comment]
> it fails saying "Original error: Server '1.2.3.4:123' not found in known_hosts" but does not complain if i use this-->

Is that host in the `known_hosts` file? If not, then spur won't connect by default, since that would be insecure.

**Comment by mwilliamson** [comment]
Closing since this doesn't look like a problem with Spur, feel free to reopen if I'm mistaken.
