### ISSUE TITLE
Can client.load_system_host_keys() be configurable?

### ISSUE THREAD

**Issue by joshbaptiste** [mwilliamson/spur.py#32]
Where I work there are many hosts that are running as fail over nodes and we consistently have hosts/key mismatch errors that we have to ignore to allow our scripts to work. These errors are causing our spur based scripts to fail prematurely in ssh.py here....
`252             client.load_system_host_keys()`
Can the load_system_host_keys() method be set as a configurable parameter?

**Comment by mwilliamson** [comment]
> Can the load_system_host_keys() method be set as a configurable parameter? 

Sounds sensible to me. I probably won't have time to look at this for a few days at least, so feel free to send in a pull request in the meantime if you want.

**Comment by mwilliamson** [comment]
I've added a `load_system_host_keys` argument to `SshShell` in the latest version (0.3.15), let me know if that doesn't work for you.
