### ISSUE TITLE
SSH Shell stuck in infinite while loop

### ISSUE THREAD

**Issue by k4r7h1k** [mwilliamson/spur.py#33]
Hi William,

I am having some odd issue where the code gets stuck in a infinite loop within _read_int_initialization_line(). I tried step through the program and it seems like variable line seems to empty all the time.

Sample Code:
```
with spur.LocalShell() as shell:
        result = shell.run(["echo", "hello"])
        print (result.output)
with spur.SshShell("*********", username="karthiks", password="********") as shell:
        result = shell.run(["echo 'hello'"])
        print (result.output)
```
The local shell works as expected, whereas the ssh shell gets stuck in infinite loop, any help is appreciated.

Thanks,
Karthik

**Comment by k4r7h1k** [comment]
I created a SshShell with `shell_type=spur.ssh.ShellTypes.minimal` and it seems to have fixed the issue. Although, not sure what caused the error in previous case, time to do some digging.

Apologies for wasting your time.

Thanks,
Karthik

**Comment by mwilliamson** [comment]
No worries, glad to hear you got it sorted.
