### ISSUE TITLE
Disable logging from Paramiko when using Spur

### ISSUE THREAD

**Issue by pwyszynski** [mwilliamson/spur.py#51]
Hello,

Is it possible to disable Paramiko's logging to debug when using Spur? I cannot seem to find an option to do this. The reason I'm trying to do this is I'm using `logging` module to log my own messages, and it get's pretty clustered with all of the Paramiko's logs.

Is there any other way to disable the logs (at least on debug level) from Paramiko when using Spur other than adding `logging.getLogger("paramiko").setLevel(logging.ERROR)` in every file where Spur is used?

**Comment by mwilliamson** [comment]
I think the snippet you've written is the best way to configure the logging for paramiko. Rather than including it in every file, you could include it in a common module, such as the top-level package (if you have one).
