### ISSUE TITLE
BSD is not compatible with license of Paramiko (LGPLv2)

### ISSUE THREAD

**Issue by SethMichaelLarson** [mwilliamson/spur.py#52]
Paramiko is licensed under LGPLv2 and seems to be very integrated into this module (not in a way that can be easily swapped out for another module) and this worries me because BSD is a much more liberal license than LGPLv2.  Although it's never been taken to court whether dynamically importing modules that are licensed under LGPL* legally counts the same as linking I would not want you or people who use this module to be exposed to legal liability because of a license compatibility issue.

Could the license be changed to reflect this or is there some reason that I am missing for this not being the case?

**Comment by mwilliamson** [comment]
I believe the LGPL permits the usage of paramiko by Python import, which appears to agree with a discussion about the license in a [paramiko issue](https://github.com/paramiko/paramiko/issues/540). Do you disagree with their interpretation, or with my interpretation of the discussion?

**Comment by SethMichaelLarson** [comment]
The problem isn't anything to do with the owners of Paramiko but rather the FSF as they are the ones who will sue for damages for infringing the license not the owner of the licensed code.  The problem comes down to the whole "`import module` isn't the same as linking" argument has no legal backing as it's never been tested in court so you're opening yourself and your users to possible consequences by licensing paramiko-dependent code under a license that's not compatible with the LGPLv2.  You're of course allowed to take this risk if you think that the importing different from linking argument would have a legal standing if it came down to it or if you just don't think it'll ever be challenged.

**Comment by mwilliamson** [comment]
Spur itself does not contain any paramiko code, and therefore no LGPL code. The user could, if they so choose, reimplement paramiko from scratch and use it with spur without any modification whatsoever to spur. Given that no LGPL code is being distributed, and that the LGPL code (i.e. paramiko) could be replaced at runtime, I believe the conditions of the license are being met.

I'm not a lawyer, but why would the FSF sue for infringement if they're not the copyright holders? So far as I know, if they're not the copyright holders, they have no right to do so.
