### ISSUE TITLE
Writing str command instead of list

### ISSUE THREAD

**Issue by gokhanm** [mwilliamson/spur.py#53]
If i'll use spur module in my project. I want to write shell commands in str variable instead of the list. I think it's easy and fast way to do this.

```python
import spur

shell = spur.LocalShell()
cmd = "echo -n hello"
result = shell.run(cmd)
print(result.output) # prints hello
```

Do you accept PR like below for local.py, shell.py etc. ?
```python
encoding = kwargs.pop("encoding", None)
cwd = kwargs.get('cwd')
command = command.split() # Return a list of the words in the string
command_in_cwd = self._shell_type.generate_run_command(command, *args, store_pid=store_pid, **kwargs)
```

**Comment by mwilliamson** [comment]
I prefer the API to require a list to avoid issues with escaping and splitting. For instance, just splitting on whitespace might give unexpected behaviour if it contains quotes.

An alternative is to run the command through an actual shell, for instance:

```python
cmd = "echo -n hello"
shell.run(["sh", "-c", cmd])
```

**Comment by gokhanm** [comment]
Yea you are right. it may cause a problem.
