### ISSUE TITLE
How to grep a file?

### ISSUE THREAD

**Issue by aligajani** [mwilliamson/spur.py#55]

**Comment by mwilliamson** [comment]
You can either invoke grep using `spawn` or `run`, or run some Python code after opening a file with `open()`.

**Comment by aligajani** [comment]
Can you please give me an example, how would I run grep "string" debug.log -c  after I have entered the directly wwe/?

**Comment by mwilliamson** [comment]
Something like `shell.run(["grep", pattern, "path/to/debug.log"])`?

**Comment by aligajani** [comment]
Thanks @mwilliamson , what would be the pattern for say getting count of words. I usually do `grep "stringToMatch" fileName.log -c`.

**Comment by mwilliamson** [comment]
What's stopping you from running that command?

**Comment by aligajani** [comment]
Sorry, I fixed it. I finally understood how it works. Thank you so much man!
