### ISSUE TITLE
Streaming output from stdout.

### ISSUE THREAD

**Issue by Xorso** [mwilliamson/spur.py#60]
I am having trouble figuring out how to stream stdout while executing `spawn`. Can you provide with some direction on how to accomplish this?

I am trying to write to a log file but stream stdout as it changes so I can watch the command being executed in realtime in the log file.

The basic example I have tried is:

```python
stdout = StringIO()

with LocalShell(...) as shell:
    proc = shell.spawn(cmd, stdout=stdout, store_pid=True)
    while proc.is_running():
        line = stdout.readline()
        if line and line != '':
            print(line)

```
Any help would be appreciated.

**Comment by Xorso** [comment]
I figured it out. I am access the proc._subprocess.stdout.

**Comment by mwilliamson** [comment]
I wouldn't recommended accessing the internal state of Spur, since that's not guaranteed to work between versions.

If you're using Python 2, you could just be able to do something like:

```python
shell.spawn(cmd, stdout=sys.stdout)
```

In Python 3, `sys.stdout` is a text file, so you'll need to get the underlying buffer:

```python
shell.spawn(cmd, sys.stdout.buffer)
```

**Comment by Xorso** [comment]
I am still not sure how to read from sys.stdout.buffer then while it is getting written too at the same time. Any thoughts?

**Comment by mwilliamson** [comment]
You can implement a tee-like file object whose write method both writes to stdout and also does whatever else you want with the output.
