### ISSUE TITLE
Python blocks until child created by run() finishes/dies

### ISSUE THREAD

**Issue by llvilanova** [mwilliamson/spur.py#61]
Whenever I run SshShell.run(), my script gets completely blocked and is unresponsive to CTRL+C. I hoped to install a signal handler for SIGINT to clean things up, but the handler only gets called after the child process finishes, as if it was queued until run() unblocks.

The same happens when I run wait_for_result() on the result of SshShell.spawn().

I also tried with SIGTERM, with the same results.

MWE:
```python
import spur
s = spur.SshShell(hostname="localhost", missing_host_key=spur.ssh.MissingHostKey.accept)
s.run(["bash", "-c", "sleep 100000"])
```

**Comment by mwilliamson** [comment]
Spur uses threading rather than multiprocessing, although it might well be the same issue. If that is the case, then I suspect the issue would be in Spur rather than Paramiko. Suggestions are welcome on how to restructure the code to avoid the issue, but I'm unlikely to have time to look at it myself.

**Comment by rsteckroth** [comment]
I solved this problem by adding a thread timeout to the reader wait call.

`    def wait(self):
        self._thread.join(10)
        return self._output
`

I think a flexible solution would be to add a thread_timeout kwarg to SshShell that gets passed along to the SshProcess and then used in the wait() call of _ContinuousReader()

Let me know if you'd like a complete patch.

**Comment by llvilanova** [comment]
I just tried that and it does not solve the problem with the example I pasted above. I'm starting to suspect the origin of the problem is in paramiko.

**Comment by llvilanova** [comment]
I've found a work around for the blocking problem. If I patch the `SshShell.run` method into this (roughly), I'm able to trigger a `KeyboardInterrupt`:

<pre>
def run(self, *args, **kwargs):
    obj = self.spawn(*args, **kwargs)
    while obj.is_running():
        time.sleep(.1)
    return obj.wait_for_result()
</pre>

Could you integrate something on those lines on a new release?

Actually, it would probably be better to patch `wait_for_result` so that no user code will block `KeyboardInterrupt` no matter if the user decides to use `run` or `spawn`.

**Comment by mwilliamson** [comment]
The problem with your suggestion is that we'll wait for up to a second longer than necessary for a process to finish. I'd suggest that the code you've got could just be used in your own codebase without modifying spur.

**Comment by llvilanova** [comment]
The sleep is for 0.1 seconds, and can be tuned arbitrarily. My curent fix is to inherit from SshShell to patch `wait_for_result` with the sleep proposed here, but I though it might be more convenient for everyone to have this fix upstreamed.

If you feel this is not the right place, feel free to close this issue.

**Comment by llvilanova** [comment]
Closing. Changes in how my script using spur is called seem to be enough to circumvent this problem in most cases without changing spur.
