### ISSUE TITLE
Allow using with pexpect

### ISSUE THREAD

**Issue by llvilanova** [mwilliamson/spur.py#64]
Hi. In some cases I need to launch some commands with `spawn`, but wait for certain text indicating it's good to go (e.g., wait for a foreground daemon to initialize).

Is there any way to use `spur` together with `pexpect`?

**Comment by mwilliamson** [comment]
I'm not familiar with pexpect, so I have no idea I'm afraid.

**Comment by llvilanova** [comment]
It's like the `expect` program, but for python: https://pexpect.readthedocs.io/en/stable/overview.html (i.e., automate interactive command-line sessions, or wait until a program shows a specific output).

`pexpect` also manages spawning of processes, albeit locally. I guess both `spur` and `pexpect` are similar in essence when spawning processes, but one cannot use the other as they are written.

**Comment by mwilliamson** [comment]
Closing since I don't there's anything to change here.
