### ISSUE TITLE
Commands only working with minimal Shell configuration

### ISSUE THREAD

**Issue by MHC03** [mwilliamson/spur.py#66]
Hi,

I would first like to thank you very much for this convenient module. 

As stated in the title I can only run commands on the cluster I connect to with the minimal Shell configuration. The Problem could lie with the cluster having tcsh as default shell configuration but I am not sure. When changing the shell to bash it worked with the normal sh Shell configuration. 
I am not sure which details you need for working on this Issue, but I would gladly try to provide any needed information.

Best reagards,

MHC

**Comment by mwilliamson** [comment]
I'm not familiar with tcsh, but it sounds like a custom shell type is
required. I'm unlikely to have time to add in support for tcsh, but
feel free to take a look yourself. The relevant code is in
`spur/ssh.py`, specifically the `MinimalShellType` and `ShShellType`
classes.

**Comment by MHC03** [comment]
Ok thank you very much, I will have a look into both classes and see what configuration is needed for being able to connect to a tcsh shell. As I also am a bit busy, I don't know if I will be able to do it and when.

**Comment by MHC03** [comment]
As seen in the Pull Request #68 I have implemented another class for the tcsh shell. 
To be honest, I also do not know tcsh that much but the class is almost equal to ShShellType, the only difference is that in the command generation " > /dev/null 2>&1" is changed to ">& /dev/null" and "cd {0} 2>&1" to "cd {0} |& cat" and all "{...}" to "(...)". So you may consider shortening this by creating some kinda base class or by specifying some strings, so that almost the same class does not exist multiple times. 
Also, as mentioned in the pull request, I have no test cases for this.
If in some cases spur does not work with other types of shell, it is most likely that the problem might be similar to this. So just search for the corresponding commands for the shell you want to implement.

Lastly I will again mention with caution, that there are no tests and I will work on another cluster which has bash as default, so I will not be using tcsh as ShellType.

**Comment by mwilliamson** [comment]
I've added a recipe for a tcsh shell type in the `recipes` directory, so I think this can be closed now.
