### ISSUE TITLE
Copying files

### ISSUE THREAD

**Issue by marko-ristin-parquery** [mwilliamson/spur.py#67]
I stumbled over your library while I was looking for a better way to organize deployment scripts which as of now consist of a long series of subprocess.check_call's. First of all, thanks a lot for your effort!

Most of our use cases can be covered with Spur's run() and spawn(), but I still miss the functionality to copy files in order to replace the manual invocation of rsync and scp via subprocess. Paramiko does support SFTP, but it's limited and would also involve certain amount of boilerplate code which I think could be nicely put beneath Spur. 

I would be happy to contribute and to implement the following extension to the shell interface.
```
# copy-only policies
IF_NOT_EXISTS=1
IF_MTIME_DIFFERENT=2
IF_MD5_DIFFERENT=3
IF_MTIME_OR_MD5_DIFFERENT=4

put(local_path: str, 
    remote_path: str, 
    create_directories: bool = True, 
    copy_only: Union[None,int] = None)->None

put_files(local_remote_paths: List[Tuple[str, str]], 
    create_directories: bool = True, 
    copy_only: Union[None,int] = None, 
    on_directory_creation: Union[None, Callable[[str], None]] = None, 
    on_put: Union[None, Callable[[str, str], None]] = None)->None

get(remote_path: str, 
    local_path: str, 
    create_directories: bool = True, 
    copy_only: Union[None,int] = None)->None

get_files(remote_local_paths: List[Tuple[str, str]], 
    create_directories: bool = True, 
    copy_only: Union[None,int] = None,
    on_directory_creation: Union[None, Callable[[str], None]] = None, 
    on_get: Union[None, Callable[[str, str] = None)->None
```

I suggest to include put_files and get_files in order to allow for more efficient directory creation. Without this optimization, copying multiple files with create_directories set to True would be very slow since we would have to check for directory existence at every put/get. The callbacks passed as arguments could serve for a nice interactive display of progress, state maintenance _etc._

On a side note, do you have any pointers how to retrieve modification times and md5 hashes from the remote files in an efficient way?

Please let me know what you think. I reserved some time in the following two weeks to implement this, so I'd be very thankful if you could respond at your earliest  convenience.

**Comment by mwilliamson** [comment]
The intention is that `put` and `get` can be supported using `open`, with the same idioms as when dealing with (say) local files. I'm not sure that adding in specific implementations of them adds that much. I'm open to being persuaded otherwise though!

For `get_files`: checking for existing local directories doesn't seem like it'd be much of a bottleneck? 

For `put_files`: if the goal is efficiency, then I've found that the only way to get reasonable performance with large numbers of files is to create an archive of files, and then unpacking them on the remote side. However, this is tricky to generalise since it depends on what the local and remote systems look like. I'd suggest the best bet would be to pipe the archive to a remote `tar x`, but I'm not sure if that's what you had in mind?

> On a side note, do you have any pointers how to retrieve modification times and md5 hashes from the remote files in an efficient way?

Nothing beyond running a script to generate the necessary output, running it on the remote system, and parsing the output. For instance, you could write a Python script to operate on local files, spit out some JSON, run it remotely using `python -c`, and then parse the JSON.

**Comment by mwilliamson** [comment]
Also, I don't think spur is missing any of the primitives to do what you've suggested, so there's certainly no reason you couldn't build something on top of spur for your specific use-case.

**Comment by marko-ristin-parquery** [comment]
Hi MIchael, 

Thanks for your response!

> The intention is that put and get can be supported using open, with the same idioms as when dealing with (say) local files. I'm not sure that adding in specific implementations of them adds that much. I'm open to being persuaded otherwise though!

> Also, I don't think spur is missing any of the primitives to do what you've suggested, so there's certainly no reason you couldn't build something on top of spur for your specific use-case.

I agree with you completely on this. The primitives are there and all this functionality can be achieved without adding these functions to Spur. 

My main idea is to use Spur for deployment script which I prefer to be succinct and as clear as possible (they tend to get messy and long, and the less boilerplate code the better). For example, you want to see immediately what is copied and where, make it easier for people unfamiliar with Spur and Paramiko (or even Python) to use it _etc._ My estimation is that there are quite a few people missing this in any of the libraries out there, but of course I might be very wrong.

> For get_files: checking for existing local directories doesn't seem like it'd be much of a bottleneck?

This is correct. I added it here just for the principle of least surprise to make it coherent with `put_files`.

> For put_files: if the goal is efficiency, then I've found that the only way to get reasonable performance with large numbers of files is to create an archive of files, and then unpacking them on the remote side. However, this is tricky to generalise since it depends on what the local and remote systems look like. I'd suggest the best bet would be to pipe the archive to a remote tar x, but I'm not sure if that's what you had in mind?

I actually thought to implement it in a much simpler way -- just copying files one by one (only the files that actually need copying). We could add later a flag `use_tar` and actually have what you propose and just pipe the tar to the remote host. 

Additionally, I would also add a `consistent` flag. If set, files are first copied to a unique temporary file (path + uuid4 suffix + ".tmp") and then renamed.

If you feel that these functions are too specific and would make Spur unnecessarily complicated, it's of course totally understandable and I'll just implement it as a separate library.

**Comment by marko-ristin-parquery** [comment]
Hi Michael!

I ended up implementing a separate library with a couple of wrapper functions. I also realized only later that there is `upload_dir()` already implemented in spur.

For all the extra functionality of `put_files` and `get_files` I'll keep using rsync; re-implementing it makes little sense as there is no easy way to implement a generic and efficient computation of md5.
