### ISSUE TITLE
Add close() to shells

### ISSUE THREAD

**Issue by LocutusOfPenguin** [mwilliamson/spur.py#71]
Hi,
i have the following:
self.shell = spur.SshShell(hostname=hostname, username=username, password=password,
                                           missing_host_key=paramiko.AutoAddPolicy())
self.engine = chess.uci.spur_spawn_engine(self.shell, [file]) # spawns a process with name "file"

INSTEAD this will work (powerdown) but here not using a ssh connection:
self.engine = chess.uci.popen_engine(file, stderr=DEVNULL)

LONG RUNNING PROGRAM talking to self.engine (send/receive commands).

Now, i want to powerdown the machine currently running this complete program. For this im using:
os.system('systemctl isolate dgtpistandby.target')

This will work if my spawn process is not using ssh. But if i use the above shell, it seems to fail.
I guess its fails cause the ssh connection is still alive.
So, i want to close this ssh session by program. How to do this?

I only saw something with (older issues)

"with ..." "run shell command"

but i cant do this here, cause the shell should stay open all the time (over lots of program lines).

Thanks,
Jürgen

**Comment by mwilliamson** [comment]
If I've understood your problem correctly, then you want to be able to
close the shell without having to use a `with` statement?

If so, you can invoke `__exit__` directly (albeit in a rather ugly
fashion):

    shell.__exit__(None, None, None)

I should probably add a proper `close()` method to the shell, but the
above should work.

**Comment by LocutusOfPenguin** [comment]
thanks for yr fast answer...Yes, that is what i wanted!

I wasnt sure, y could understand all this strange code, i posted (tried to leave away the uninteresting stuff).
I need to take a look for it - so, i leave this open for a while, ok?

**Comment by mwilliamson** [comment]
A `close()` method has been added in the latest version, so closing this issue.
