### ISSUE TITLE
Add spur to awesome-python

### ISSUE THREAD

**Issue by mristin** [mwilliamson/spur.py#80]
Hi,
I made a pull request to add spur to the curated list of awesome python modules:
https://github.com/vinta/awesome-python/pull/1113

Please let me know if you want to change something in the description. It would be cool if at least 20 people  thumb up the pull request if they think that it's meaningful to put spur on that list.

**Comment by mwilliamson** [comment]
Thanks for the suggestion, alas spur is not popular enough from the looks of things! I'm also not sure how easy paramiko is to use these days -- it might well be the case you're better off just using paramiko directly.
