### ISSUE TITLE
Shell.run() Errors on sudo sed command

### ISSUE THREAD

**Issue by jwashington104** [mwilliamson/spur.py#82]
Hi there, I'm having an issue using shell.run() to run a sed command as sudo. 

Here's my sample.

`result = shell.run(['sudo', 'sed', '-i', '-r', '\"s~recovery_target_time = \'[0-9\]{4}-[0-9]{2}-[0-9]{2} [0-9\]{2}:[0-9]{2}:[0-9]{2}\'~recovery_target_time = \'__TESTING__\'~g\" /var/lib/pgsql/9.6/data/recovery.conf'], use_pty=True`

This is the error I get: 

> output: b'sed: -e expression #1, char 1: unknown command: `"\'\r\n'

Any Ideas?

**Comment by mwilliamson** [comment]
It sounds like there's a newline in the string being passed to sed. Could you post the original code?

**Comment by mwilliamson** [comment]
Closing since I don't think there's anything further to investigate without the code.
