### ISSUE TITLE
spur fails to connect but with same configuration paramiko works

### ISSUE THREAD

**Issue by snehalbiche** [mwilliamson/spur.py#84]
I am not sure what the issue with spur, but tried paramiko and it able to connect and run command -

few points to note :- 
1) These VM network is in different vlans, each vlan assigned to respective network card.
2) These VM has multiple networks - e.g 
eth0: 192.168.159.121
eth0.0: 192.168.159.120
eth1: 10.122.122.41
eth1.0: 10.10.122.45
eth2: 192.168.165.121
eth2.0: 192.168.165.120
eth3: 192.168.160.121
lo: 127.0.0.1

3) These VM are able to connect to each other using any ip and name, even paramiko able to, so no configuration issue

4) but spur works for the IP which is assigned to eth1 and eth1.0, but not able to eth0, eht0.0, eth2, eth2.0 and even with machine name spur fails to connect. might be the same ip is assigned to multiple NIC and spur gets confused? and on my system eth0 ip is by default configured in /etc/hosts file so wanted to use default set IP to reduce configuration required. 

5) below is the error -
/usr/local/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:39: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  m.add_string(self.Q_C.public_numbers().encode_point())
/usr/local/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:96: CryptographyDeprecationWarning: Support for unsafe construction of public numbers from encoded data will be removed in a future version. Please use EllipticCurvePublicKey.from_encoded_point
  self.curve, Q_S_bytes
/usr/local/lib/python3.6/site-packages/paramiko/kex_ecdh_nist.py:111: CryptographyDeprecationWarning: encode_point has been deprecated on EllipticCurvePublicNumbers and will be removed in a future version. Please use EllipticCurvePublicKey.public_bytes to obtain both compressed and uncompressed point encoding.
  hm.add_string(self.Q_C.public_numbers().encode_point())
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/spur/ssh.py", line 266, in _get_ssh_transport
    return self._connect_ssh().get_transport()
  File "/usr/local/lib/python3.6/site-packages/spur/ssh.py", line 286, in _connect_ssh
    sock=self._sock
  File "/usr/local/lib/python3.6/site-packages/paramiko/client.py", line 414, in connect
    raise BadHostKeyException(hostname, server_key, our_key)
paramiko.ssh_exception.BadHostKeyException: ('lb01', <paramiko.rsakey.RSAKey object at 0x7f101802b940>, <paramiko.rsakey.RSAKey object at 0x7f10182c19e8>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "spurssh.py", line 5, in <module>
    result = shell.run(["echo", "-n", "hello"])
  File "/usr/local/lib/python3.6/site-packages/spur/ssh.py", line 166, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File "/usr/local/lib/python3.6/site-packages/spur/ssh.py", line 178, in spawn
    channel = self._get_ssh_transport().open_session()
  File "/usr/local/lib/python3.6/site-packages/spur/ssh.py", line 268, in _get_ssh_transport
    raise self._connection_error(error)
spur.ssh.ConnectionError: Error creating SSH connection
Original error: ('lb01', <paramiko.rsakey.RSAKey object at 0x7f101802b940>, <paramiko.rsakey.RSAKey object at 0x7f10182c19e8>)

**Comment by mwilliamson** [comment]
Could you post the code you're using for both spur and paramiko?

**Comment by snehalbiche** [comment]
here is the code  -
Paramiko - 
==========================
        shell = paramiko.SSHClient()
        if self.ssh_path_to_private_key:
             shell.load_system_host_keys(self.ssh_path_to_private_key)
             shell.load_host_keys(self.ssh_path_to_private_key)
             shell.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        shell.connect(node, port=port, timeout=30, username=self.user)

        self.logger.info("Executing '%s' on %s" % (cmd, node))
        #pdb.set_trace()
        try:
          with shell:
            stdin, stdout, stderr = shell.exec_command(cmd)
            #print("printing stdout", stdout.read().decode())
            #print("printing ret_code", stdout.channel.recv_exit_status())
            results[node] = {
               "stdout": stdout.read().decode(),
               "ret_code": stdout.channel.recv_exit_status()
            }
        except Exception as e:
           results[node] = {
             "ret_code": 1,
             "error": str(e),
           }

           self.logger.info("Executing '%s' on %s failed with error: %s" % (cmd, node, str(e)))

SPUR - 
==========================
           shell = spur.SshShell(
              hostname=self.override_host or node.ip,
              username=self.user,
              missing_host_key=self.missing_host_key,
              private_key_file=self.ssh_path_to_private_key,
          )
        self.logger.info("Executing '%s' on %s" % (cmd_full, node.name))
        try:
          with shell:
           output = shell.run(cmd_full)
           results[node.ip] = {
              "ret_code": output.return_code,
              "stdout": output.output.decode(),
              "stderr": output.stderr_output.decode(),
           }
        except Exception as e:
          results[node.ip] = {
            "ret_code": 1,
            "error": str(e),
          }
          self.logger.info("Executing '%s' on %s failed with error: %s" % (cmd_full, node.name, str(e)))

**Comment by mwilliamson** [comment]
From comparing the two sets of code, it looks like the system host keys aren't being imported when you use paramiko (since you explicitly set the path to a different file), but is by default in Spur. You could try passing `load_system_host_keys=False` to Spur.
