### ISSUE TITLE
spur.results.RunProcessError: return code: 127

### ISSUE THREAD

**Issue by LEscobar-Driver** [mwilliamson/spur.py#86]
Return code 127 means a non-existing-command. I am trying to change the directory but am unable to because the 'cd' command seems to be non-existing. Any idea what is going on? All other commands seems to be working fine. 

result = shell.run(["cd", "/mnt"])

**Comment by mwilliamson** [comment]
`cd` isn't an executable, which is why you're seeing an error. If you want to execute a command in a different directory, use the `cwd` argument.

**Comment by LEscobar-Driver** [comment]
How am I suppose to change directories?

**Comment by mwilliamson** [comment]
If you want to list a directory, you can either pass the argument directly to ls:

```
shell.run(["ls", "/path/to/directory"])
```

or use the `cwd` argument:

```
shell.run(["ls"], cwd="/path/to/directory")
```
