### ISSUE TITLE
Support for later paramiko

### ISSUE THREAD

**Issue by fabaff** [mwilliamson/spur.py#96]
`paramiko-3.0.0` was [released](https://www.paramiko.org/changelog.html) a while back. `setup.py` says `paramiko>=1.13.1,<3`. 

Any change to get support for `paramiko` > 3.0.0? Thanks.

This is primary an issue for distributions which are shipping `spur`, not for the users who are using it in a `venv`.

**Comment by mwilliamson** [comment]
Thanks for the report, support for paramiko 3 is now in `master`.

**Comment by fabaff** [comment]
Thank you very much.
