### ISSUE TITLE
Can't run windows commands

### ISSUE THREAD

**Issue by dbernstein-pallidus** [mwilliamson/spur.py#97]
I know spur was written with unix in mind so perhaps this issue is off-base. I'm using it to ssh to a windows machine. The sample code is (XX means redacted)

shell = spur.SshShell(
        hostname=XX,
        port=XX
        username=XX,
        password=XX,
        missing_host_key=spur.ssh.MissingHostKey.accept,
        shell_type=spur.ssh.ShellTypes.minimal,
    )

    result = shell.run(["dir"], encoding="UTF-8")
    print(result.output)

This is the output:
stderr output:
''dir'' is not recognized as an internal or external command,
operable program or batch file.

It appears what it is trying to do is to execute the command 'dir', i.e., literally the word dir with quotes around it. Of course this string is not a windows command. Is there a simple way around this?

**Comment by mwilliamson** [comment]
You'll need to write your own shell type to match up with whatever the escaping rules are that Windows expects. I'm afraid I'm not familiar enough to know exactly what that would be.

**Comment by dbernstein-pallidus** [comment]
Thanks, I thought it would be something like that. If I try it, I'll let you know how it goes.
